apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  project: blog
  sources:
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: gitops/argocd-apps/blog
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: charts/blog
      helm:
        valueFiles:
          - $values/gitops/apps/blog/values.yaml
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: .
      ref: values
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: gitops/apps/blog/sealedsecrets
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
