apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "1.18.0"
      helm:
        valueFiles:
          - $values/gitops/apps/system/cert-manager/values.yaml
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: .
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
