{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "basic-auth",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "basic-auth",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "BASIC_AUTH_PASSWORD": "AgBw7249X2cPcmxQGjoXmNiUQ+1gsNZqZlDZT4LZKbWhF4j1RzLx8rHW156AR2cXsKewQkGhW/Ukxbjj/7q7lsEI//HdoAudVJ0QNGjDFJ9d0h7W1Hsyoh4md0TH1gO/uXwufYZOHsbl2+JgiZFRG3+fX0mr3Cz6NbNkfwd3gIRiI/cxSgVLWrHVlwfLu6uxkHta+x+WyT/vESEf7UnXOpYRqp0SbsQPlINXVkBDjVcWyEi/emYaNWYFeSbdBswtpqD0MhAyzBXDnG6V52AfzyTrirO2L0xAhyhaH9xCAJJyhSRZBdWv3bXSayhOHp9OQHR1cVOfnVL0fjPfBNnJlk5Q1RhOv972TidcTLvLZa1MEMB1LXTjAJ7ViKxNqk5reYt/GKr10tQ9hiG4XLt7x9RXUlmbIyhsin5OO+QHTxyPBex3Z1q0ZbrhPho/uc059WmemIenpc92nCnty6QEyeIsOMZ82P/FgtdVjKTjMp21L1l2V6ivGzxCybYHYWDz5c6ksyXc5gjlyjenUcD34NNVImIzDsKac19TtELvxD7tEvvJGc7cnwmMYB4s0+eldVjlU2AfwzHxJiHw765ZEzVWRvCDEyECy1pgOfRfvDR3gxQo2/tZCTQ4ieGATKS9STfNY/J1RT/DV5sQPc7UtsBkyDwJsTZShTHmxBDMtoni9RDmnnjNaBj9rRA5ceUjmq8eEQr2NMIPnGfFuXN75U6Yt8tZFw==",
      "BASIC_AUTH_USER": "AgAL4eHkh6rUgVqOd1IRA0c/ag5IaFTmLF+nmJilr8s2rAiSH5T6qVG9MAwIdxMHZMSKiY8neEciq0+Tq9ryNLdzZMdIGCKQ0mqh8hbOkyqdjBiYbwQFjaqfiGF+Bzyrqs3s+3rglY3n/w4AYp4DJ03h0pZrQKfE2ZpCLqi1EEMuikjfDiHcgKIU0AjQTuQqjHmQWKJA5mT7NtemitjgTKvLIXw5C1/3B686EObk0NzbPP+uMbPO2LMGGTfrrIUskoczg8EkSbGRTANw9BbVtr7e/D4oi6thfK74xYVlGkO4m4q3vOLKJWjQdkpAUkKrigEPNMjTAqSNvXFnljRwKk4lwIRCWGcL3yrOeUTKaq7b2n2T01VKuFNvQ7ZfkOk3xKEsjeHG1zXEInblA+THwh2VmPxMOvWH1RSBnoWz9a3C8ZUO0TS9iCV4QLbMfeyuq6lE+4DaWy0zpfCHsYNPs5yDGJr+TY3x6qztyvSDzRVQM53eWPLMDZzACenbK4SBzkItwH5KqQ04prwQ4dl4mU0B3ukWhVsMDE3A8ii5yQ+oSSwHulRQWEPTsv955diyyWClYdIRJCSrKJTpfuA6dOjTVslHFYmbRjBK3f2aguZFi3oBAFaOyQITRcj50E9u0ZjpyBREvketnS9he+W44V3E8xNE3lEpZ+yl1pZWMAPXxGbnQp3+bNJwJP6KuFvzAlSDi7vuFQ=="
    }
  }
}
