---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: codex-on-air
spec:
  encryptedData:
    .dockerconfigjson: AgBH5shz1EUYn4vHAP0Af6cSG7Q5XicaYEEBP39HKz5rOTbYV4uGutvuJk51wC7ylvjO866Oo2PdrEQJJgYEN4tqJIPxkW9KPlVLEcY7L/kEyrtLYMqxbXUN9qRyVBvnGTBwdklAcrv47LYjRrMo2uUE4hoJ2W8iYEw81bN5otUjpHE8l1hIdrt3iPT0uIfcxRjFbdfu42/fg4gL33QTeGcKgY+2f7x0g5ru0TGWklKzWiz53QqUnpwYypTEZ9PKwzomLFpKrVgFJf4gmxfOSvuzxio1X4UyHD31r3cWs7vKE/9NlvQwU3WOXc8CWrvrZ+INYTiaqd8ht0w0edLgAV0laQECfWfA8ukGXZMp5H27k8sD5QwBnOomeZeBfQkP+Pc6DOPGkl7yYk+rE2e7qP3hIohyeN6Y+M0QRo9ajJt4wHpwuf1fcmf3qeiLO+tSn2Jv2Poq1VKHWMq6vRwLtKs3Y0OUGDDjQlcc9KduylZQpEqF1iH19vTvQ7VI/447rlAkKaCUEhyJ5Zif/zXsGsvncd+k91iZjW49nV3EK8Idq86BU+BFDPwPNG7TOGg58cxvseQFUv7L1CfKrFYvNoIdRcm0zsXamip9jtF0oMqgePkjHh20y9xSKiNF8kwWPhay5gLky8q324VZT7AQ4wts0MgIaRJydtfgXAmGh1UaYpYS1IeNCkIuZcpxg3XYg6L63K80nKhJqMf92MfoLUXZzJ19EGa4dLLcEBGKaiQf/L1+AwEXaOPD8EgfQrDi3gjZk36n4YGH7mrEaUNv51WUkqscJJMeoSR5VGRCb73/xVTrhOKIxt0xJCQWbVuZF87qJODSSucB01W785x303snumaNlMH/PWFRqRnx/p9XVmyYPbgYkzmTrDkgghlzIECvwHSyIzysV/7G2wSNHG+cwGQfojn9NMt4aQXVAvfCMKlzVQ==
  template:
    metadata:
      name: ghcr-pull
      namespace: codex-on-air
    type: kubernetes.io/dockerconfigjson
