---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: codex-on-air
spec:
  encryptedData:
    .dockerconfigjson: AgDMIAxXnzL3d2wD3QIh2hinVtrh5IOjTcV70MCm8bUC37PLqIxM4pCI0DrSYB2XBOnLTY8eEeymeRg396Qge5VEjC6OJlmxKk2dOPQjhoVdNC+8QmhcbhXYeu9nb6k1jn1k4ahoTdehjdyzQ3uT8It6uMSXyX4qMRF9D+ciYQ4l8nFi5knKzxjRnnh/ezrMfUKeiN1MmyqQAmJjL7Ecy+mHelXEzXGTAKJe0VBNudA8bbO3pBp+TJxAtC0H3U97kEboUgyV9yFPqAm06x1+MtMF3XVs4bdKYJCDIJlgGRR93Ui2PU6T/oB/Qmg5FAeWm/WEQxSNdNG1kD5obtAmgXDGRcRD9XCSPQpfMSxMxOzbjWpdB7zEPk483nWiAdEtBup5SzfZPBrOIWdbbrDj2P01H5Oz/MFkV+Z2eX0AAJ2hDFYInp08LfOOr97AWYSD+vTMfrJ2lojJatR0QQ+Qg32r/I8ELiLneThXci9N0dOIoljMGOf75dtMv0BF6jH2GD6zG6N8XpTaBarxN+iM9WQgRZ/NCPub//cRVXs2i8HZcyfUwliBY3WJVe3DEHkB00XI0QF0tCp7qFRgc42POyIf8sWOY/PjA+3qj2hg7UJozW4yioJDIM+86mt6oGAoeHqBtbzyq+BIVtFHVW/sOGHqIgu2uSFDKmDTruU1ulE0FWyBg+nuf/lp0gk2IXVImTZ3CP2UuPCgn0W/81dI9FGAqndKPtsxDyHP0VhNwnZdUh6unhpxQXT8T73MIMfPKvD38sNJrqY2sUuyhEJ8boEp9RzqvAImriaMszmpUvzfgiLtKi/ilK9VagvbWGyvDWRFWTTY3kbHQrWKaZaNXXvb9yI3KE4ITVk3/kvvY3dOsHKCjfg0H86CJHBCFbnINyNr+TGKCaXXvuOH5vy9BJXlSi0CfOi/BzC2t8W42+u9IYJpS8KE0qLcwIx9bwCCxO9/fb4wQ0lfU9j2Z4HeqxiVWFYtPCRvOgkEyEK2keXMjoK12z0VL3HOxRsJbzDt0rfjE9HNT5jdK6CDp02ESzapKa6d2mlJ5hhCIfmbm9Y5cHNXEWAfTP36OQzTpUhpd+HsdiDETSm4kjODxUfDNuJD
  template:
    metadata:
      name: ghcr-pull
      namespace: codex-on-air
    type: kubernetes.io/dockerconfigjson
