apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
    name: collector
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch: {}
    exporters:
      otlphttp:
        endpoint: http://k8s-monitoring-alloy-receiver.k8smonitoring.svc.cluster.local:4318
        tls: { insecure: true }
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlphttp]