{{- range $project, $apps := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project }}
  namespace: argocd
spec:
  description: {{ $project }} workloads
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  {{- range $app, $_ := $apps }}
    - server: https://kubernetes.default.svc
      namespace: {{ $app }}
  {{- end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}
