envValueFrom:
  BASIC_AUTH_USER:
    secretKeyRef:
      name: basic-auth
      key: BASIC_AUTH_USER
  BASIC_AUTH_PASSWORD:
    secretKeyRef:
      name: basic-auth
      key: BASIC_AUTH_PASSWORD

replicas: 1
ingress:
  enabled: true
  ingressClassName: "traefik"
  path: /
  pathType: Prefix
  hosts:
    - grafana.garnaudov.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.garnaudov.com

grafana.ini:
  server:
    domain: grafana.garnaudov.com
    root_url: https://grafana.garnaudov.com

persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Logs Blog
      - name: Logs Arena
    datasources:
      - name: Metrics
        type: prometheus
        uid: mimir
        orgId: 1
        url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
        access: proxy
        isDefault: true
        basicAuth: true
        basicAuthUser: $__env{BASIC_AUTH_USER}
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "default"
          timeInterval: 60s
          basicAuthPassword: $__env{BASIC_AUTH_PASSWORD}
      - name: Logs
        type: loki
        uid: loki
        orgId: 1
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
        basicAuth: true
        basicAuthUser: $__env{BASIC_AUTH_USER}
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "default"
          basicAuthPassword: $__env{BASIC_AUTH_PASSWORD}
      - name: Tempo
        type: tempo
        uid: tempo
        orgId: 1
        url: http://tempo-gateway.tempo.svc.cluster.local
        access: proxy
        basicAuth: true
        basicAuthUser: $__env{BASIC_AUTH_USER}
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "default"
          basicAuthPassword: $__env{BASIC_AUTH_PASSWORD}
