cluster:
  name: "ubuntu-16gb-fsn1-1"

global:
  scrapeInterval: 15s

destinations:
  - name: mimir
    type: prometheus
    url: "https://mimir.garnaudov.com/api/v1/push"
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    tenantIdKey: tenantId
    secret:
      create: false
      name: destinations-auth
  - name: loki
    type: loki
    url: "https://loki.garnaudov.com/loki/api/v1/push"
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: destinations-auth
  - name: tempo
    type: otlp
    protocol: http
    url: "https://otlp.garnaudov.com/otlp"
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: destinations-auth
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true

clusterMetrics:
  enabled: true
  destinations:
    - mimir
  kubelet:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: []
      excludeMetrics: []
  kubeletResource:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: []
      excludeMetrics: []
  cadvisor:
    enabled: true
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: []
      excludeMetrics: []
  kube-state-metrics:
    enabled: true
    deploy: true
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: []
      excludeMetrics: []
  node-exporter:
    enabled: true
    deploy: true
    metricsTuning:
      useDefaultAllowList: false
      useIntegrationAllowList: false
      includeMetrics: []
      excludeMetrics: []
      dropMetricsForFilesystem: []
  windows-exporter:
    enabled: false
    deploy: false

alloy-metrics:
  enabled: true

clusterEvents:
  enabled: true
  destinations:
    - loki

alloy-singleton:
  enabled: true

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  destinations:
    - loki

alloy-logs:
  enabled: true

applicationObservability:
  enabled: true
  destinations:
    - mimir
    - loki
    - tempo
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318

alloy-receiver:
  enabled: true
  destinations:
    - tempo
  alloy:
    enableReporting: false
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

selfReporting:
  enabled: false
