projects:
  system:
    argocd:
      chart:
        repoURL: https://argoproj.github.io/argo-helm
        name: argo-cd
        version: 9.1.3
      extraResources:
        - sealedsecrets
      namespace: argocd
    sealed-secrets:
      chart:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        name: sealed-secrets
        version: 2.17.9
      namespace: kube-system
    cert-manager:
      chart:
        repoURL: https://charts.jetstack.io
        name: cert-manager
        version: 1.18.0
      namespace: cert-manager
    cloudnative-pg:
      chart:
        repoURL: https://cloudnative-pg.github.io/charts
        name: cloudnative-pg
        version: 0.28.0
      namespace: cnpg-system
      syncWave: "-20"
      syncOptions:
        - ServerSideApply=true
  monitoring:
    grafana:
      chart:
        repoURL: https://grafana-community.github.io/helm-charts
        name: grafana
        version: 12.3.0
      extraResources:
        - sealedsecrets
      namespace: grafana
  sites:
    blog:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: blog
        version: 0.1.0
      extraResources:
        - sealedsecrets
      namespace: blog
    codex-on-air-db:
      chart:
        repoURL: https://cloudnative-pg.github.io/charts
        name: cluster
        version: 0.6.0
      extraResources:
        - sealedsecrets
      namespace: codex-on-air
      syncWave: "-10"
      syncOptions:
        - SkipDryRunOnMissingResource=true
    codex-on-air:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: codex-on-air
        version: 0.2.0
      extraResources:
        - sealedsecrets
      namespace: codex-on-air
      syncWave: "0"
  arena:
    web-frontend:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: web-frontend
        version: 0.1.2
      extraResources:
        - sealedsecrets
      namespace: arena
    gateway-service:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: gateway-service
        version: 0.2.1
      extraResources:
        - sealedsecrets
      namespace: arena
    gamestate-service:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: gamestate-service
        version: 0.1.0
      namespace: arena
    matchmaking-service:
      chart:
        repoURL: ghcr.io/gd-arnold/cluster/charts
        name: matchmaking-service
        version: 0.2.1
      namespace: arena
