apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: "8.6.4"
      helm:
        valueFiles:
          - $values/gitops/apps/monitoring/grafana/values.yaml
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: .
      ref: values
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: gitops/apps/monitoring/grafana/sealedsecrets
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
