apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: k8s-monitoring
      targetRevision: "3.4.0"
      helm:
        valueFiles:
          - $values/gitops/apps/monitoring/k8s-monitoring/values.yaml
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: .
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: k8smonitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true