apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: "5.8.0"
      helm:
        valueFiles:
          - $values/gitops/apps/monitoring/mimir/values.yaml
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: .
      ref: values
    - repoURL: git@github.com:gd-arnold/cluster.git
      targetRevision: main
      path: gitops/apps/monitoring/mimir/sealedsecrets
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
