apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: "0.93.1"
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
